store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

store/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',  views.store, name='home'),
    path('<int:id>/<slug:slug>/',  views.product_detail, name='product_detail'),
    #   path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    # path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/cart/models.py
from django.db import models

# Create your models here.

store/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Имя категории')
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField(upload_to='categories/', blank=True, null=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name='Название продукта')
    description = models.TextField(blank=True, verbose_name='Описание продукта')
    slug = models.SlugField(max_length=50)
    image = models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')
    available = models.BooleanField(default=True, verbose_name='В наличии')
    pub_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    old_price = models.DecimalField(blank=True, null=True, max_digits=8, decimal_places=2, verbose_name='Старая цена')

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-pub_date']),
        ]
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

store/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data  # это метод FORMS
        """
        возвращает словарь проверенных полей ввода формы и их значений,
        где строковые первичные ключи возвращаются как объекты.
        """
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

store/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from .paginator import paginator

def store(request):
    products = Product.objects.filter(available=True).order_by('?')
    context = {'page_obj': paginator(request, products, 6),
               'other_product': paginator(request, products, 3)}
    return render(request, 'shop/product/main_page.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request, 'shop/product/detail.html', {'product': product})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, Slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})

store/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
 Your shopping cart
{% endblock %}

{% block content %}
<div class="checkout">
    <div class="container">
        <div class="cart__shopping">
            <h1>Корзина</h1>
            <div class="checkout__wrapper">
                {% for item in cart %}
                    {% with product=item.product %}
                        <div class="checkout__block">
                            <div class="checkout__table">
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="checkout__img" src="{% if product.image %}{{ product.image.url }}
                                    {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="product_image">
                                </a>
                                <div class="checkout__table-item">
                                    <h3>{{ product.name }}</h3>
                                    <div class="select">
                                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                            {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.override }}
                                        <input type="submit" value="Update">
                                            {% csrf_token %}
                                        </form>
                                    </div>
                                </div>
                                <div class="checkout__actions">
                                    <a href="#" class="checkout__remove">
                                        <img src="{% static 'image/delete.svg' %}" alt="">
                                    </a>
                                    <div class="checkout__price">
                                        ${{ product.price }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endwith %}
                {% endfor %}
                <div class="block__bay">
                    <div class="block__info-bay">
                        <div class="checkout__price">
                            <div class="checkout__total-row">
                                <div class="title">Цена</div>
                                <div class="count">${{ item.price }}</div>
                            </div>
                            <div class="checkout__total-row">
                                <div class="title">Доставка</div>
                                <div class="count">$10</div>
                            </div>
                            <div class="total__price">
                                <div class="title">Итоговая цена</div>
                                <div class="count">${{ item.total_price }}</div>
                            </div>
                        </div>
                        <button class="btn btn-main btn-full" type="submit" >Оформить заказ</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en-ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Main page{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<header class="header">
    <div class="header__line">
        <div class="container">
            <div class="header__line-wrapper">
                <div class="header__lng">
                    <a href="#">Ru</a>
                    <a href="#" class="active">En</a>
                </div>
                <a  href="#" class="header__phone">+7-999-999-99-99</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="header__wrapper">
            <div class="header__block">
                <nav class="nav">
                    <a href="/" class="nav__link active">Главная</a>
                    <a href="#" class="nav__link">О нас</a>     <!--ссылка о нас-->
                    <a href="#" class="nav__link">Каталог</a>      <!--ссылка меню-->
                    <a href="#" class="nav__link">Контакты</a>       <!--ссылка резервации-->
                </nav>
            </div>

            <a href="/" class="logo">
                <img src="{% static 'img/logo/coffee_logo.png' %}" alt="coffee_logo">
            </a>

            <div class="header__block right">
                <div class="header__actions">
<!--                    <a href="#" class="header__link">-->
<!--                        <img src="{% static 'img/user.svg' %}" alt="user_img">-->
<!--                    </a>-->
                    <a href="#">
                        <img src="{% static 'img/favorite.svg' %}" alt="favorite_img">
                    </a>
                    <a href="{% url 'cart:cart_detail' %}">
                        <img src="{% static 'img/cart.svg' %}" alt="cart_img">
                        <span class="header__link-event"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>   <!-- /.header-->
{% block content %} {% endblock %}
<footer class="footer">
    <div class="container">
        <div class="footer__wrapper">
            <div class="footer__block">
                <a class="footer__logo" href="/">
                    <img src="{% static 'img/logo/logo_footer.png' %}" alt="logo_image_button">
                </a>
            </div>

            <div class="footer__block">
                <nav class="nav nav-footer">
                    <a href="/" class="nav__link">Главная</a>
                    <a href="#" class="nav__link">О нас</a>
                    <a href="#" class="nav__link">Каталог</a>
                </nav>
            </div>

            <div class="footer__block">
                <nav class="nav nav-footer">
                    <a href="#" class="nav__link">Контакты</a>
                    <a href="#" class="nav__link">Политика<br>конфиденциальности</a>
                </nav>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

store/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="products__bay">
    <div class="container">
        <div class="product">
            <div class="block__title">
                <h1>{{ product.name }}</h1>
                <div class="product__wrapper">
                    <div class="product__image">
                        <div class="product__item">
                            <img class="product__picture" src="{% if product.image %}{{ product.image.url }}
                            {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="product_picture">
                        </div>
                    </div>
                    <div class="product__info">
                        <div class="product__item">
                            <div class="product__price">
                                ${{ product.price }}
                                <del>
                                    {% if product.old_price %}${{ product.old_price }}
                                    {% else %} {% endif %}
                                </del>
                            </div>

                            <form class="product__form" action="{% url 'cart:cart_add' product.id %}" method="post">
                                <--не отображается на сайте->
                                {{ cart_product_form }}
                                {% csrf_token %}
                                <--не отображается на сайте->
                                <button class="btn btn-main btn-full" type="submit" >Add to cart</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="product__fotter">
                    <div class="block__title">
                        <h3 class="products__name">
                            Описание
                        </h3>
                    </div>
                    <div class="product__item">
                        {{ product.description|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
        <!--Похожие продукты-->
        <h3 class="block__titel">
            Похожие товары
        </h3>
        <div class="products__wrapper">
            <--не отображается на сайте->
            {% for product in other_product %}
                <div class="products__block">
                    <a class="products__item" href="{{ product.get_absolute_url }}">
                        <img class="products__img" src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="products__img">

                        <h3 class="products__name">{{ product.name }}</h3>

                        <div class="products__footer">
                            <div class="products__price">
                                ${{ product.price }}
                            <del>
                                {% if product.old_price %}${{ product.old_price }}
                                {% else %} {% endif %}
                            </del>
                            </div>
                            <button type="button" class="products__favorite">
                                <img src="{% static 'img/favorite.svg' %}" alt="favorite_img">
                            </button>
                        </div>
                    </a>
                </div>
            {% endfor %}
            <--не отображается на сайте->
        </div>
        <!-- /.Похожие продукты-->
    </div>
</div>
{% endblock %}

store/shop/templates/shop/product/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

<header class="header">
    <div class="header__line">
        <div class="container">
            <div class="header__line-wrappper">
                <div class="header__lng">
                    <a href="#">Ru</a>
                    <a href="#" class="active">En</a>
                </div>
                <a  href="#" class="header__phone">+7-999-999-99-99</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="header__wrapper">
            <div class="header__block">
                <nav class="nav">
                    <a href="#" class="nav__link active">Home</a>
                    <a href="#" class="nav__link">About</a>
                    <a href="#" class="nav__link">Menu</a>
                    <a href="#" class="nav__link">Reservation</a>
                </nav>
            </div>

            <a href="#" class="logo">
                <img src="image/logo/coffee_logo.png" alt="coffee_logo">
            </a>

            <div class="header__block right">
                <div class="header__actions">
                    <a href="#" class="header__link">
                        <img src="image/user.svg" alt="user_img">
                    </a>
                    <a href="#">
                        <img src="image/favorite.svg" alt="favorite_img">
                    </a>
                    <a href="#">
                        <img src="image/cart.svg" alt="cart_img">
                        <span class="header__link-event"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>   <!-- /.header-->

<div class="intro" style="background-image: url('image/bg/coffee_img.jpg');">
    <div class="container">
        <div class="intro__wrapper">
            <div class="intro__block">
                <h1 class="intro__title">Roasted coffee best choice</h1>
                <p class="intro__text">
                    The coffee is brewed by first roasting the green coffee beans over hot<br> 
                    coals in a brazier. given an opportunity to sample.
                </p>
                <div class="intro__actions">
                    <a class="btn btn-main" href="#">Buy now</a>
                    <a class="btn btn-secodary" href="#">read more</a>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /.intro -->

<div class="info">
    <div class="container">
        <div class="info__block">
            <div class="info__img-wrapper">
                <img class="image__info" src="image/coffee_info.png" alt="coffee_info_img">
            </div>
            <div class="info__item">
                <div class="info__titel">
                    <h1>Rosted Coffe</h1>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.</p>
                </div>
            </div>
        </div>    
    </div>
</div>  <!-- /.info-->

<div class="products">
    <div class="container">
        <h2 class="block__titel">
            catalog
        </h2>

        <div class="products__wrapper">
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_1.png" alt="products__img">
    
                    <h3 class="products__name">Lavazza coffee</h3>
    
                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_2.png" alt="products__img">
    
                    <h3 class="products__name">Lavazza coffee</h3>
    
                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_1.png" alt="products__img">
    
                    <h3 class="products__name">Lavazza coffee</h3>
    
                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_1.png" alt="products__img">
    
                    <h3 class="products__name">Lavazza coffee</h3>
    
                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_2.png" alt="products__img">

                    <h3 class="products__name">Lavazza coffee</h3>

                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
            <div class="products__block">
                <!-- ССЫЛКУ НЕ ЗАБУДСЬ ПОСТАВИТ -->
                <a class="products__item" href="#">
                    <img class="products__img" src="image/products/product_1.png" alt="products__img">

                    <h3 class="products__name">Lavazza coffee</h3>

                    <div class="products__footer">
                        <div class="products__price">
                            $19.99
                        <del>$29.99</del>
                        </div>
                        <button type="button" class="products__favorite">
                            <img src="image/favorite.svg" alt="favorite_img">
                        </button>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>  <!-- /.products-->

<div class="news">
    <div class="container">
        <div class="news__title">
            <h2>news</h2>
        </div>
        <div class="news__wrapper">
            <div class="news__block">
                <a class="news__item" href="#">
                    <img class="news__img" src="image/news/new_1.png" alt="new_image_1">
                    <div class="news__content">
                        <h3>Lavazza coffee</h3>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>    
                    </div>
               </a>
            </div>

            <div class="news__block">
                <a class="news__item" href="">
                    <img class="news__img" src="image/news/new_2.png" alt="new_image_1">
                    <div class="news__content">
                        <h3>Lavazza coffee</h3>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>    
                    </div>
               </a>
            </div>
            <div class="news__block">
                <a class="news__item" href="">
                    <img class="news__img" src="image/news/new_3.png" alt="new_image_1">
                    <div class="news__content">
                        <h3>Lavazza coffee</h3>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>    
                    </div>
               </a>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="footer__wrapper">
            <div class="footer__block">
                <a class="footer__logo" href="#">
                    <img src="image/logo/logo_footer.png" alt="logo_imape_button">
                </a>
            </div>

            <div class="footer__block">
                <nav class="nav nav-footer">
                    <a href="#" class="nav__link">Home</a>
                    <a href="#" class="nav__link">About</a>
                    <a href="#" class="nav__link">Menu</a>
                    <a href="#" class="nav__link">Reservation</a>
                </nav>
            </div>

            <div class="footer__block">
                <nav class="nav nav-footer">
                    <a href="#" class="nav__link">Contacts</a>
                    <a href="#" class="nav__link">Privacy policy</a>
                </nav>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

store/shop/templates/shop/product/main_page.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<div class="intro" style="background-image: url('../../../static/img/bg/coffee_img.jpg');">
    <div class="container">
        <div class="intro__wrapper">
            <div class="intro__block">
                <h1 class="intro__title">ЖАРЕНЫЙ КОФЕ ЛУЧШИЙ ВЫБОР</h1>
                <p class="intro__text">
                    кофе арабика является отличным источником кофеина - натурального стимулятора,
                    который помогает повысить уровень энергии, улучшить умственную концентрацию и общее самочувствие.

                </p>
                <div class="intro__actions">
                    <a class="btn btn-main" href="#">Купить</a>
                    <a class="btn btn-secodary" href="#">читать далее</a>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /.intro -->

<div class="info">
    <div class="container">
        <div class="info__block">
            <div class="info__img-wrapper">
                <img class="image__info" src="{% static 'img/coffee_info.png' %}" alt="coffee_info_img">
            </div>
            <div class="info__item">
                <div class="info__titel">
                    <h1>Жареный кофе</h1>
                    <p>
                        Было доказано, что кофе арабика обладает и другими потенциальными преимуществами
                        для здоровья, такими как снижение риска развития некоторых видов болезней,
                        улучшение физической работоспособности и даже снижение риска инсульта и других
                        сердечно-сосудистых заболеваний. Считается, что эти преимущества обусловлены наличием
                        в кофе различных соединений, таких как хлорогеновая кислота и кахвеол, которые,
                        как было доказано, оказывают положительное влияние на здоровье. В заключение следует отметить,
                        что кофе арабика - это вкусный и питательный напиток, который может предложить
                        широкий спектр преимуществ для здоровья.
                    </p>
                </div>
            </div>
        </div>    
    </div>
</div>  <!-- /.info-->

<div class="products">
    <div class="container">
        <h2 class="block__titel">
            каталог
        </h2>
        <div class="products__wrapper">
            {% for product in page_obj %}
                <div class="products__block">
                    <a class="products__item" href="{{ product.get_absolute_url }}">
                        <img class="products__img" src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="products__img">
                        <h3 class="products__name">{{ product.name }}</h3>
                        <div class="products__footer">
                            <div class="products__price">
                                ${{ product.price }}
                            <del>
                                {% if product.old_price %}${{ product.old_price }}
                                {% else %} {% endif %}
                            </del>
                            </div>
                            <button type="button" class="products__favorite">
                                <img src="{% static 'img/favorite.svg' %}" alt="favorite_img">
                            </button>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>  <!-- /.products-->

<div class="news">
    <div class="container">
        <div class="news__title">
            <h2>Новости</h2>
        </div>
        <div class="news__wrapper">
            <div class="news__block">
                <a class="news__item" href="#">
                    <img class="news__img" src="{% static 'img/news/new_1.png' %}" alt="new_image_1">
                    <div class="news__content">
                        <h3>Заголовок приложения</h3>
                        <p>Текст для приложения "Новости"</p>
                    </div>
               </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}